// packages/sdks/client-sdks/gatrix-svelte-client-sdk/examples/dashboard/src/components/ConfirmDialog.svelte
<script lang="ts">
  export let title: string;
  export let message: string;
  export let onConfirm: () => void;
  export let onCancel: () => void;
</script>

<div class="confirm-overlay">
  <div class="nes-container is-dark with-title confirm-dialog rumble-on-pop">
    <p class="title" style="background-color:#000">{title}</p>
    <p class="confirm-message">{message}</p>
    <div class="confirm-buttons">
      <button type="button" class="nes-btn" on:click={onCancel}>CANCEL</button>
      <button type="button" class="nes-btn is-error" on:click={onConfirm}>POWER OFF</button>
    </div>
  </div>
</div>

// packages/sdks/client-sdks/gatrix-vue-sdk/examples/dashboard/src/components/ConfirmDialog.vue
<script setup lang="ts">
defineProps<{ title: string; message: string }>();
const emit = defineEmits<{ (e: 'confirm'): void; (e: 'cancel'): void }>();
</script>

<template>
  <div class="confirm-overlay">
    <div class="nes-container is-dark with-title confirm-dialog rumble-on-pop">
      <p class="title" style="background-color: #000">{{ title }}</p>
      <p class="confirm-message">{{ message }}</p>
      <div class="confirm-buttons" style="display: flex; gap: 12px; justify-content: center">
        <button type="button" class="nes-btn" @click="emit('cancel')">CANCEL</button>
        <button type="button" class="nes-btn is-error" @click="emit('confirm')">POWER OFF</button>
      </div>
    </div>
  </div>
</template>
