// packages/sdks/client-sdks/gatrix-react-sdk/examples/dashboard/src/components/DisconnectScreen.tsx
import { useState, useEffect } from 'react';

interface DisconnectScreenProps {
  onComplete: () => void;
}

const DISCONNECT_MESSAGES = [
  { text: 'DISCONNECTING FROM GATRIX...', delay: 0 },
  { text: '', delay: 300 },
  { text: 'SAVING SESSION DATA... OK', delay: 500 },
  { text: 'CLOSING CONNECTIONS... OK', delay: 1000 },
  { text: 'CLEARING CACHE... OK', delay: 1500 },
  { text: '', delay: 1800 },
  { text: 'GOODBYE!', delay: 2000 },
];

function DisconnectScreen({ onComplete }: DisconnectScreenProps) {
  const [visibleMessages, setVisibleMessages] = useState<string[]>([]);
  const [showGoodbye, setShowGoodbye] = useState(false);

  useEffect(() => {
    const timers: NodeJS.Timeout[] = [];

    // Show messages progressively
    DISCONNECT_MESSAGES.forEach((msg) => {
      const timer = setTimeout(() => {
        setVisibleMessages((prev) => [...prev, msg.text]);
      }, msg.delay);
      timers.push(timer);
    });

    // Show goodbye character after last message
    const goodbyeTimer = setTimeout(() => {
      setShowGoodbye(true);
    }, 2200);
    timers.push(goodbyeTimer);

    // Complete 2.5 seconds after goodbye
    const completeTimer = setTimeout(() => {
      onComplete();
    }, 4700); // 2200 + 2500
    timers.push(completeTimer);

    return () => {
      timers.forEach((t) => clearTimeout(t));
    };
  }, [onComplete]);

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100vh',
        backgroundColor: '#212529',
        color: '#fff',
        fontFamily: '"Press Start 2P", cursive',
        textAlign: 'center',
        padding: '24px',
      }}
    >
      <div style={{ minHeight: '200px', marginBottom: '24px' }}>
        {visibleMessages.map((msg, i) => (
          <div
            key={i}
            style={{
              fontSize: '10px',
              marginBottom: '8px',
              color: msg === 'GOODBYE!' ? '#e76e55' : '#adafbc',
            }}
          >
            {msg || '\u00A0'}
          </div>
        ))}
        {showGoodbye && (
          <div
            style={{
              marginTop: '16px',
              animation: 'sad-sway 1s ease-in-out infinite',
            }}
          >
            <i className="nes-bcrikko"></i>
          </div>
        )}
      </div>
    </div>
  );
}

export default DisconnectScreen;

// packages/sdks/client-sdks/gatrix-vue-sdk/examples/dashboard/src/components/DisconnectScreen.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

const emit = defineEmits<{ (e: 'complete'): void }>();

const DISCONNECT_MESSAGES = [
  { text: 'DISCONNECTING FROM GATRIX...', delay: 0 },
  { text: '', delay: 300 },
  { text: 'SAVING SESSION DATA... OK', delay: 500 },
  { text: 'CLOSING CONNECTIONS... OK', delay: 1000 },
  { text: 'CLEARING CACHE... OK', delay: 1500 },
  { text: '', delay: 1800 },
  { text: 'GOODBYE!', delay: 2000 },
];

const visibleMessages = ref<string[]>([]);
const showGoodbye = ref(false);
const timers: ReturnType<typeof setTimeout>[] = [];

onMounted(() => {
  DISCONNECT_MESSAGES.forEach((msg) => {
    const t = setTimeout(() => {
      visibleMessages.value.push(msg.text);
    }, msg.delay);
    timers.push(t);
  });

  timers.push(setTimeout(() => { showGoodbye.value = true; }, 2200));
  timers.push(setTimeout(() => { emit('complete'); }, 4700));
});

onUnmounted(() => { timers.forEach((t) => clearTimeout(t)); });
</script>

<template>
  <div
    :style="{
      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      height: '100vh', backgroundColor: '#212529', color: '#fff',
      fontFamily: '\'Press Start 2P\', cursive', textAlign: 'center', padding: '24px',
    }"
  >
    <div style="min-height: 200px; margin-bottom: 24px">
      <div
        v-for="(msg, i) in visibleMessages"
        :key="i"
        :style="{
          fontSize: '10px', marginBottom: '8px',
          color: msg === 'GOODBYE!' ? '#e76e55' : '#adafbc',
        }"
      >
        {{ msg || '\u00A0' }}
      </div>
      <div v-if="showGoodbye" style="margin-top: 16px; animation: sad-sway 1s ease-in-out infinite">
        <i class="nes-bcrikko"></i>
      </div>
    </div>
  </div>
</template>
