// packages/sdks/client-sdks/gatrix-svelte-client-sdk/examples/dashboard/src/components/ConfirmDialog.svelte
<script lang="ts">
  export let title: string;
  export let message: string;
  export let onConfirm: () => void;
  export let onCancel: () => void;
</script>

<div class="confirm-overlay">
  <div class="nes-container is-dark with-title confirm-dialog rumble-on-pop">
    <p class="title" style="background-color:#000">{title}</p>
    <p class="confirm-message">{message}</p>
    <div class="confirm-buttons">
      <button type="button" class="nes-btn" on:click={onCancel}>CANCEL</button>
      <button type="button" class="nes-btn is-error" on:click={onConfirm}>POWER OFF</button>
    </div>
  </div>
</div>

// packages/sdks/client-sdks/gatrix-react-client-sdk/examples/dashboard/src/components/ConfirmDialog.tsx
interface ConfirmDialogProps {
  title: string;
  message: string;
  onConfirm: () => void;
  onCancel: () => void;
}

function ConfirmDialog({ title, message, onConfirm, onCancel }: ConfirmDialogProps) {
  return (
    <div className="confirm-overlay">
      <div className="nes-container is-dark with-title confirm-dialog rumble-on-pop">
        <p className="title" style={{ backgroundColor: '#000' }}>
          {title}
        </p>
        <p className="confirm-message">{message}</p>
        <div className="confirm-buttons">
          <button type="button" className="nes-btn" onClick={onCancel}>
            CANCEL
          </button>
          <button type="button" className="nes-btn is-error" onClick={onConfirm}>
            POWER OFF
          </button>
        </div>
      </div>
    </div>
  );
}

export default ConfirmDialog;
